
name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-tauri:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Build Tauri app
      run: |
        npm install -g @tauri-apps/cli@latest
        tauri build --verbose
      env:
        TAURI_BUNDLE_IDENTIFIER: com.lovable.billingbuddy

    - name: Upload Tauri artifacts
      uses: actions/upload-artifact@v4
      with:
        name: billing-buddy-tauri-windows
        path: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/nsis/*.exe
          src-tauri/target/release/billing-buddy.exe

  build-electron:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Add Electron Builder
      run: npm install --save-dev electron-builder

    - name: Build React app
      run: npm run build

    - name: Build Electron app
      run: npx electron-builder --win --x64 --publish never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Electron artifacts
      uses: actions/upload-artifact@v4
      with:
        name: billing-buddy-electron-windows
        path: |
          dist/*.exe
          dist/*.msi
          dist/*.zip

  create-release:
    needs: [build-tauri, build-electron]
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download Tauri artifacts
      uses: actions/download-artifact@v4
      with:
        name: billing-buddy-tauri-windows
        path: ./tauri-release

    - name: Download Electron artifacts
      uses: actions/download-artifact@v4
      with:
        name: billing-buddy-electron-windows
        path: ./electron-release

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tauri-release/**/*
          electron-release/**/*
        body: |
          ## Billing Buddy Windows Release
          
          This release contains both Tauri and Electron versions:
          
          **Tauri Version (Recommended):**
          - Smaller file size (~10MB)
          - Better performance
          - More secure
          - Files: `*.msi` and `*.exe` from tauri folder
          
          **Electron Version:**
          - Larger file size (~150MB)
          - Universal compatibility
          - Files: `*.exe` and `*.msi` from electron folder
          
          **Installation:**
          1. Download either the `.msi` installer or `.exe` portable version
          2. Run the installer or executable
          3. The app will work completely offline and independent of any browser
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
