name: Build Paint Shop Billing System

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
        
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Install dependencies
      run: npm ci

    - name: Setup Tauri
      run: npm install -g @tauri-apps/cli

    - name: Build Tauri app
      run: npm run tauri:build
      env:
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

    - name: Upload Windows Installer (MSI)
      uses: actions/upload-artifact@v4
      if: matrix.platform == 'windows-latest'
      with:
        name: paint-shop-billing-windows-msi
        path: src-tauri/target/release/bundle/msi/*.msi

    - name: Upload Windows Installer (NSIS)
      uses: actions/upload-artifact@v4
      if: matrix.platform == 'windows-latest'
      with:
        name: paint-shop-billing-windows-nsis
        path: src-tauri/target/release/bundle/nsis/*.exe

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      if: matrix.platform == 'windows-latest'
      with:
        name: paint-shop-billing-windows-exe
        path: src-tauri/target/release/paint-shop-billing.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows MSI
      uses: actions/download-artifact@v4
      with:
        name: paint-shop-billing-windows-msi
        path: ./dist

    - name: Download Windows NSIS
      uses: actions/download-artifact@v4
      with:
        name: paint-shop-billing-windows-nsis
        path: ./dist

    - name: Download Windows EXE
      uses: actions/download-artifact@v4
      with:
        name: paint-shop-billing-windows-exe
        path: ./dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/*.msi
          dist/*.exe
        name: Paint Shop Billing System v${{ github.ref_name }}
        body: |
          ## Paint Shop Billing System v${{ github.ref_name }}
          
          ### Features
          - Complete Asian Paints product management
          - Invoice generation with GST support
          - Customer management
          - SQL database for data persistence
          - Silent printing support
          - Thermal printer support
          - Beautiful reports and analytics
          - Product color/code management
          - QR code payment integration
          
          ### Installation
          1. Download the `.msi` installer for standard installation
          2. Or download the `.exe` installer for portable installation
          3. Run the installer and follow the setup wizard
          
          ### System Requirements
          - Windows 10 or later
          - .NET Framework 4.7.2 or later
          - Minimum 4GB RAM
          - 500MB available disk space
          
          ### What's New
          - Enhanced database performance with SQLite
          - Improved silent printing functionality
          - Better Asian Paints product management
          - Enhanced UI with colorful design
          - Advanced reporting features
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}