
name: Build Electron App

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clean workspace
        run: |
          if (Test-Path "node_modules") { Remove-Item -Recurse -Force "node_modules" }
          if (Test-Path "dist") { Remove-Item -Recurse -Force "dist" }
          if (Test-Path "dist-electron") { Remove-Item -Recurse -Force "dist-electron" }

      - name: Install dependencies
        run: npm ci --force
        env:
          NODE_ENV: development

      - name: Install terser explicitly
        run: npm install terser --save-dev --force

      - name: Verify critical dependencies
        run: |
          npm list terser
          npm list vite
          npm list electron
          npm list electron-builder

      - name: Build React app for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Verify React build output
        run: |
          if (!(Test-Path "dist")) {
            Write-Error "React build failed - dist folder not found"
            exit 1
          }
          if (!(Test-Path "dist/index.html")) {
            Write-Error "React build failed - index.html not found"
            exit 1
          }
          Write-Host "React build successful"
          Get-ChildItem -Path "dist" -Recurse | Select-Object Name, Length

      - name: Build Electron app
        run: npm run dist
        env:
          NODE_ENV: production

      - name: Verify Electron build output
        run: |
          if (!(Test-Path "dist-electron")) {
            Write-Error "Electron build failed - dist-electron folder not found"
            exit 1
          }
          Write-Host "Electron build successful"
          Get-ChildItem -Path "dist-electron" -Recurse | Select-Object Name, Length

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: billing-buddy-windows
          path: |
            dist-electron/*.exe
            dist-electron/*.msi
            dist-electron/*.zip
        if: always()

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: billing-buddy-windows
          path: ./artifacts
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
